// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIk7l36XcBxPiiYp98CnSh6Tru_6yERRU',
    appId: '1:639631344301:web:a2f1d51e945fc3e947bc24',
    messagingSenderId: '639631344301',
    projectId: 'phone-auth-microservice',
    authDomain: 'phone-auth-microservice.firebaseapp.com',
    storageBucket: 'phone-auth-microservice.appspot.com',
    measurementId: 'G-Y2Z35GTLXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-xjVnY-XmvNulkDB1x1taAq7XCVN04I',
    appId: '1:639631344301:android:991aed4c3c94201047bc24',
    messagingSenderId: '639631344301',
    projectId: 'phone-auth-microservice',
    storageBucket: 'phone-auth-microservice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN3br91OwAOajiLWig73StnemWa9ncMPA',
    appId: '1:639631344301:ios:bdda01e8fc73fd8c47bc24',
    messagingSenderId: '639631344301',
    projectId: 'phone-auth-microservice',
    storageBucket: 'phone-auth-microservice.appspot.com',
    iosBundleId: 'ru.alaamashkouk.phoneAuthMicroservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN3br91OwAOajiLWig73StnemWa9ncMPA',
    appId: '1:639631344301:ios:2575e3da4595447147bc24',
    messagingSenderId: '639631344301',
    projectId: 'phone-auth-microservice',
    storageBucket: 'phone-auth-microservice.appspot.com',
    iosBundleId: 'ru.alaamashkouk.phoneAuthMicroservice.RunnerTests',
  );
}
